stages:
  - build

cache:
  paths:
    - .venv/
    - .cache/pip
    - .cache/pypoetry
    - artemis

image: python:3.10

before_script:
  - python --version
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

build:
  stage: build
  script:
    - REPO_URL=https://fein:$PUSH_ACCESS_TOKEN@git.fim.uni-passau.de/fein/artemis-changelog.git
    - git remote add pushable $REPO_URL || git remote set-url pushable $REPO_URL
    - poetry run python ./artemis_changelog/main.py --output-dir=changelog
    - git checkout $CI_DEFAULT_BRANCH
    - git config --global user.email "fein@fim.uni-passau.de"
    - git config --global user.name "Benedikt Fein"
    - git add changelog
    - git commit -m "scheduled update"
    - git push -o ci.skip pushable changelog
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
